using Refit;
using System.Threading.Tasks;

namespace Checkout.PaymentGateway.Domain.Clients
{
    // An http client is autogenerated from this interface using Refit - uses the registered httpclientfactory.
    public interface IAcquiringBankClient
    {
        [Post("/payments/")]
        Task<AcquiringBankPaymentResponse> PostAsync(AcquiringBankPaymentRequest request);
    }
}
